# Generated by Django 4.2.7 on 2023-11-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_alter_customerdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
